[package]
name = "file-link"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.3"
tokio = { version = "1", features = ["full"] }
tungstenite = "0.15.0"
tokio-tungstenite = "0.15.0"
futures-util = "0.3.15"